### ISSUE TITLE
external declarations become val

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#60]
I don't really know what is the intention of an `external` declaration in a module signature...

Neither this library nor ocamldoc support documenting this bit of mli files, instead changing those declarations to `val`s.

**Comment by lpw25** [comment]
It is generally considered to be a misfeature in OCaml, and its removal has been debated before. However, we should try to accurately reflected what OCaml does rather than what it should do, so I think this should indeed be considered a bug (although one that will be fixed in `doc-ock` rather than `opam-doc-base`).

**Comment by lpw25** [comment]
Fixed in doc-ock-lib
